# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mode.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1010, 609)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/main/ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MenuWidget = QtWidgets.QWidget(Form)
        self.MenuWidget.setObjectName("MenuWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.MenuWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.MixpushButton = QtWidgets.QPushButton(self.MenuWidget)
        self.MixpushButton.setObjectName("MixpushButton")
        self.gridLayout.addWidget(self.MixpushButton, 6, 1, 1, 1)
        self.OutputLabel = QtWidgets.QLabel(self.MenuWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.OutputLabel.setFont(font)
        self.OutputLabel.setObjectName("OutputLabel")
        self.gridLayout.addWidget(self.OutputLabel, 0, 0, 1, 1)
        self.OutPutSQLButton = QtWidgets.QPushButton(self.MenuWidget)
        self.OutPutSQLButton.setObjectName("OutPutSQLButton")
        self.gridLayout.addWidget(self.OutPutSQLButton, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 6, 3, 1, 1)
        self.OutExcelButton = QtWidgets.QPushButton(self.MenuWidget)
        self.OutExcelButton.setObjectName("OutExcelButton")
        self.gridLayout.addWidget(self.OutExcelButton, 1, 1, 1, 2)
        self.CementDateButton = QtWidgets.QPushButton(self.MenuWidget)
        self.CementDateButton.setObjectName("CementDateButton")
        self.gridLayout.addWidget(self.CementDateButton, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 3, 1, 1)
        self.InSQLButton = QtWidgets.QPushButton(self.MenuWidget)
        self.InSQLButton.setObjectName("InSQLButton")
        self.gridLayout.addWidget(self.InSQLButton, 3, 1, 1, 1)
        self.BasicInformationLabel = QtWidgets.QLabel(self.MenuWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.BasicInformationLabel.setFont(font)
        self.BasicInformationLabel.setObjectName("BasicInformationLabel")
        self.gridLayout.addWidget(self.BasicInformationLabel, 2, 0, 1, 2)
        self.horizontalLayout.addWidget(self.MenuWidget)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setMouseTracking(False)
        self.stackedWidget.setTabletTracking(False)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.OutExcelPage = QtWidgets.QWidget()
        self.OutExcelPage.setObjectName("OutExcelPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.OutExcelPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 3, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 3, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 3, 7, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 3, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 3, 6, 1, 1)
        self.ChangePrarmerButton = QtWidgets.QPushButton(self.OutExcelPage)
        self.ChangePrarmerButton.setObjectName("ChangePrarmerButton")
        self.gridLayout_2.addWidget(self.ChangePrarmerButton, 2, 3, 1, 1)
        self.OutPutButton = QtWidgets.QPushButton(self.OutExcelPage)
        self.OutPutButton.setEnabled(False)
        self.OutPutButton.setObjectName("OutPutButton")
        self.gridLayout_2.addWidget(self.OutPutButton, 2, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 3, 0, 1, 3)
        self.TipLabel = QtWidgets.QLabel(self.OutExcelPage)
        self.TipLabel.setText("")
        self.TipLabel.setObjectName("TipLabel")
        self.gridLayout_2.addWidget(self.TipLabel, 0, 0, 2, 1)
        self.ConcreteUsageRecordLabel = QtWidgets.QLabel(self.OutExcelPage)
        self.ConcreteUsageRecordLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.ConcreteUsageRecordLabel.setObjectName("ConcreteUsageRecordLabel")
        self.gridLayout_2.addWidget(self.ConcreteUsageRecordLabel, 0, 2, 1, 3)
        self.ConcreteUsageRecordPath = QtWidgets.QLineEdit(self.OutExcelPage)
        self.ConcreteUsageRecordPath.setEnabled(False)
        self.ConcreteUsageRecordPath.setDragEnabled(False)
        self.ConcreteUsageRecordPath.setReadOnly(True)
        self.ConcreteUsageRecordPath.setObjectName("ConcreteUsageRecordPath")
        self.gridLayout_2.addWidget(self.ConcreteUsageRecordPath, 0, 5, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.OutExcelPage)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.ConUseBuyRecordPage = QtWidgets.QWidget()
        self.ConUseBuyRecordPage.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.ConUseBuyRecordPage.setObjectName("ConUseBuyRecordPage")
        self.label_2 = QtWidgets.QLabel(self.ConUseBuyRecordPage)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_2.setObjectName("label_2")
        self.Project1Manager = QtWidgets.QComboBox(self.ConUseBuyRecordPage)
        self.Project1Manager.setGeometry(QtCore.QRect(80, 10, 69, 22))
        self.Project1Manager.setObjectName("Project1Manager")
        self.label_3 = QtWidgets.QLabel(self.ConUseBuyRecordPage)
        self.label_3.setGeometry(QtCore.QRect(200, 10, 51, 16))
        self.label_3.setObjectName("label_3")
        self.Project1FillSheeter = QtWidgets.QComboBox(self.ConUseBuyRecordPage)
        self.Project1FillSheeter.setGeometry(QtCore.QRect(250, 10, 69, 22))
        self.Project1FillSheeter.setObjectName("Project1FillSheeter")
        self.toolBox.addItem(self.ConUseBuyRecordPage, "")
        self.ConStrengReportPage = QtWidgets.QWidget()
        self.ConStrengReportPage.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.ConStrengReportPage.setObjectName("ConStrengReportPage")
        self.C_Strengthlabel = QtWidgets.QLabel(self.ConStrengReportPage)
        self.C_Strengthlabel.setGeometry(QtCore.QRect(10, 0, 194, 12))
        self.C_Strengthlabel.setObjectName("C_Strengthlabel")
        self.linelabel_1 = QtWidgets.QLabel(self.ConStrengReportPage)
        self.linelabel_1.setGeometry(QtCore.QRect(58, 20, 36, 20))
        self.linelabel_1.setObjectName("linelabel_1")
        self.MinC_StrengthEdit = QtWidgets.QLineEdit(self.ConStrengReportPage)
        self.MinC_StrengthEdit.setGeometry(QtCore.QRect(10, 18, 51, 20))
        self.MinC_StrengthEdit.setObjectName("MinC_StrengthEdit")
        self.MaxC_StrengthEdit = QtWidgets.QLineEdit(self.ConStrengReportPage)
        self.MaxC_StrengthEdit.setGeometry(QtCore.QRect(100, 20, 62, 20))
        self.MaxC_StrengthEdit.setObjectName("MaxC_StrengthEdit")
        self.Project2Checker = QtWidgets.QComboBox(self.ConStrengReportPage)
        self.Project2Checker.setGeometry(QtCore.QRect(290, 50, 81, 22))
        self.Project2Checker.setObjectName("Project2Checker")
        self.Project2Try = QtWidgets.QComboBox(self.ConStrengReportPage)
        self.Project2Try.setGeometry(QtCore.QRect(470, 50, 81, 22))
        self.Project2Try.setObjectName("Project2Try")
        self.label_93 = QtWidgets.QLabel(self.ConStrengReportPage)
        self.label_93.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.label_93.setObjectName("label_93")
        self.Project2Manager = QtWidgets.QComboBox(self.ConStrengReportPage)
        self.Project2Manager.setGeometry(QtCore.QRect(130, 50, 81, 22))
        self.Project2Manager.setObjectName("Project2Manager")
        self.label_94 = QtWidgets.QLabel(self.ConStrengReportPage)
        self.label_94.setGeometry(QtCore.QRect(250, 50, 31, 16))
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.ConStrengReportPage)
        self.label_95.setGeometry(QtCore.QRect(410, 50, 51, 16))
        self.label_95.setObjectName("label_95")
        self.Project2InspectCodeEdit = QtWidgets.QLineEdit(self.ConStrengReportPage)
        self.Project2InspectCodeEdit.setGeometry(QtCore.QRect(310, 20, 151, 20))
        self.Project2InspectCodeEdit.setObjectName("Project2InspectCodeEdit")
        self.Inspection_UnitLabel_4 = QtWidgets.QLabel(self.ConStrengReportPage)
        self.Inspection_UnitLabel_4.setGeometry(QtCore.QRect(250, 20, 71, 16))
        self.Inspection_UnitLabel_4.setObjectName("Inspection_UnitLabel_4")
        self.toolBox.addItem(self.ConStrengReportPage, "")
        self.ConStrengReportSumPage = QtWidgets.QWidget()
        self.ConStrengReportSumPage.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.ConStrengReportSumPage.setObjectName("ConStrengReportSumPage")
        self.Project3MakeSheet = QtWidgets.QComboBox(self.ConStrengReportSumPage)
        self.Project3MakeSheet.setGeometry(QtCore.QRect(80, 10, 81, 22))
        self.Project3MakeSheet.setObjectName("Project3MakeSheet")
        self.label_92 = QtWidgets.QLabel(self.ConStrengReportSumPage)
        self.label_92.setGeometry(QtCore.QRect(20, 10, 51, 16))
        self.label_92.setObjectName("label_92")
        self.Inspection_UnitLabel_3 = QtWidgets.QLabel(self.ConStrengReportSumPage)
        self.Inspection_UnitLabel_3.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.Inspection_UnitLabel_3.setObjectName("Inspection_UnitLabel_3")
        self.Project3InspectCodeEdit = QtWidgets.QLineEdit(self.ConStrengReportSumPage)
        self.Project3InspectCodeEdit.setGeometry(QtCore.QRect(80, 40, 151, 20))
        self.Project3InspectCodeEdit.setObjectName("Project3InspectCodeEdit")
        self.toolBox.addItem(self.ConStrengReportSumPage, "")
        self.ConStrengReportCompPage = QtWidgets.QWidget()
        self.ConStrengReportCompPage.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.ConStrengReportCompPage.setObjectName("ConStrengReportCompPage")
        self.label_89 = QtWidgets.QLabel(self.ConStrengReportCompPage)
        self.label_89.setGeometry(QtCore.QRect(220, 10, 31, 16))
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.ConStrengReportCompPage)
        self.label_90.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_90.setObjectName("label_90")
        self.Project4Manager = QtWidgets.QComboBox(self.ConStrengReportCompPage)
        self.Project4Manager.setGeometry(QtCore.QRect(100, 10, 81, 22))
        self.Project4Manager.setObjectName("Project4Manager")
        self.Project4Calculate = QtWidgets.QComboBox(self.ConStrengReportCompPage)
        self.Project4Calculate.setGeometry(QtCore.QRect(440, 10, 81, 22))
        self.Project4Calculate.setObjectName("Project4Calculate")
        self.label_91 = QtWidgets.QLabel(self.ConStrengReportCompPage)
        self.label_91.setGeometry(QtCore.QRect(380, 10, 51, 16))
        self.label_91.setObjectName("label_91")
        self.Project4Checker = QtWidgets.QComboBox(self.ConStrengReportCompPage)
        self.Project4Checker.setGeometry(QtCore.QRect(260, 10, 81, 22))
        self.Project4Checker.setObjectName("Project4Checker")
        self.Project4InspectCodeEdit = QtWidgets.QLineEdit(self.ConStrengReportCompPage)
        self.Project4InspectCodeEdit.setGeometry(QtCore.QRect(80, 40, 151, 20))
        self.Project4InspectCodeEdit.setObjectName("Project4InspectCodeEdit")
        self.Inspection_UnitLabel_2 = QtWidgets.QLabel(self.ConStrengReportCompPage)
        self.Inspection_UnitLabel_2.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.Inspection_UnitLabel_2.setObjectName("Inspection_UnitLabel_2")
        self.toolBox.addItem(self.ConStrengReportCompPage, "")
        self.CreateConFacyoryCardPage = QtWidgets.QWidget()
        self.CreateConFacyoryCardPage.setGeometry(QtCore.QRect(0, 0, 722, 203))
        self.CreateConFacyoryCardPage.setObjectName("CreateConFacyoryCardPage")
        self.label_14 = QtWidgets.QLabel(self.CreateConFacyoryCardPage)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_14.setObjectName("label_14")
        self.Project5Filler = QtWidgets.QComboBox(self.CreateConFacyoryCardPage)
        self.Project5Filler.setGeometry(QtCore.QRect(250, 10, 69, 22))
        self.Project5Filler.setObjectName("Project5Filler")
        self.label_16 = QtWidgets.QLabel(self.CreateConFacyoryCardPage)
        self.label_16.setGeometry(QtCore.QRect(200, 10, 51, 16))
        self.label_16.setObjectName("label_16")
        self.Project5Manager = QtWidgets.QComboBox(self.CreateConFacyoryCardPage)
        self.Project5Manager.setGeometry(QtCore.QRect(80, 10, 69, 22))
        self.Project5Manager.setObjectName("Project5Manager")
        self.toolBox.addItem(self.CreateConFacyoryCardPage, "")
        self.SlumpCardPage = QtWidgets.QWidget()
        self.SlumpCardPage.setGeometry(QtCore.QRect(0, 0, 722, 203))
        self.SlumpCardPage.setObjectName("SlumpCardPage")
        self.toolBox.addItem(self.SlumpCardPage, "")
        self.ConMixDesignPage = QtWidgets.QWidget()
        self.ConMixDesignPage.setGeometry(QtCore.QRect(0, 0, 722, 203))
        self.ConMixDesignPage.setObjectName("ConMixDesignPage")
        self.MinS_SurfaceDensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinS_SurfaceDensityEdit.setGeometry(QtCore.QRect(120, 20, 51, 20))
        self.MinS_SurfaceDensityEdit.setObjectName("MinS_SurfaceDensityEdit")
        self.MaxS_SurfaceDensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxS_SurfaceDensityEdit.setGeometry(QtCore.QRect(200, 20, 51, 20))
        self.MaxS_SurfaceDensityEdit.setObjectName("MaxS_SurfaceDensityEdit")
        self.MinS_FinenessDensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinS_FinenessDensityEdit.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.MinS_FinenessDensityEdit.setText("")
        self.MinS_FinenessDensityEdit.setObjectName("MinS_FinenessDensityEdit")
        self.label_5 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 21, 20))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_8.setGeometry(QtCore.QRect(170, 20, 21, 20))
        self.label_8.setObjectName("label_8")
        self.S_FinenessDensityLabel = QtWidgets.QLabel(self.ConMixDesignPage)
        self.S_FinenessDensityLabel.setGeometry(QtCore.QRect(10, 0, 84, 12))
        self.S_FinenessDensityLabel.setObjectName("S_FinenessDensityLabel")
        self.MaxS_FinenessDensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxS_FinenessDensityEdit.setGeometry(QtCore.QRect(70, 20, 41, 20))
        self.MaxS_FinenessDensityEdit.setObjectName("MaxS_FinenessDensityEdit")
        self.S_SurfaceDensityLabel = QtWidgets.QLabel(self.ConMixDesignPage)
        self.S_SurfaceDensityLabel.setGeometry(QtCore.QRect(120, 0, 84, 12))
        self.S_SurfaceDensityLabel.setObjectName("S_SurfaceDensityLabel")
        self.label_9 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_9.setGeometry(QtCore.QRect(320, 20, 21, 20))
        self.label_9.setObjectName("label_9")
        self.MinS_DensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinS_DensityEdit.setGeometry(QtCore.QRect(270, 20, 51, 20))
        self.MinS_DensityEdit.setObjectName("MinS_DensityEdit")
        self.MaxS_DensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxS_DensityEdit.setGeometry(QtCore.QRect(350, 20, 51, 20))
        self.MaxS_DensityEdit.setObjectName("MaxS_DensityEdit")
        self.S_DensityLabel = QtWidgets.QLabel(self.ConMixDesignPage)
        self.S_DensityLabel.setGeometry(QtCore.QRect(270, 0, 103, 12))
        self.S_DensityLabel.setObjectName("S_DensityLabel")
        self.MaxS_SlitContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxS_SlitContentEdit.setGeometry(QtCore.QRect(480, 20, 41, 20))
        self.MaxS_SlitContentEdit.setObjectName("MaxS_SlitContentEdit")
        self.S_SlitContentLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.S_SlitContentLabel_2.setGeometry(QtCore.QRect(420, 0, 84, 14))
        self.S_SlitContentLabel_2.setObjectName("S_SlitContentLabel_2")
        self.MinS_SlitContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinS_SlitContentEdit.setGeometry(QtCore.QRect(420, 20, 41, 20))
        self.MinS_SlitContentEdit.setObjectName("MinS_SlitContentEdit")
        self.label_13 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_13.setGeometry(QtCore.QRect(460, 20, 21, 20))
        self.label_13.setObjectName("label_13")
        self.MaxS_WaterContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxS_WaterContentEdit.setGeometry(QtCore.QRect(600, 20, 41, 20))
        self.MaxS_WaterContentEdit.setObjectName("MaxS_WaterContentEdit")
        self.label_15 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_15.setGeometry(QtCore.QRect(580, 20, 21, 20))
        self.label_15.setObjectName("label_15")
        self.S_WaterContentLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.S_WaterContentLabel_2.setGeometry(QtCore.QRect(540, 0, 78, 14))
        self.S_WaterContentLabel_2.setObjectName("S_WaterContentLabel_2")
        self.MinS_WaterContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinS_WaterContentEdit.setGeometry(QtCore.QRect(540, 20, 41, 20))
        self.MinS_WaterContentEdit.setObjectName("MinS_WaterContentEdit")
        self.G_GrainContentLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.G_GrainContentLabel_2.setGeometry(QtCore.QRect(10, 50, 84, 14))
        self.G_GrainContentLabel_2.setObjectName("G_GrainContentLabel_2")
        self.label_17 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_17.setGeometry(QtCore.QRect(50, 70, 21, 20))
        self.label_17.setObjectName("label_17")
        self.MaxG_GrainContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxG_GrainContentEdit.setGeometry(QtCore.QRect(70, 70, 41, 20))
        self.MaxG_GrainContentEdit.setObjectName("MaxG_GrainContentEdit")
        self.label_19 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_19.setGeometry(QtCore.QRect(160, 70, 16, 20))
        self.label_19.setObjectName("label_19")
        self.MaxG_CrushLevelEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxG_CrushLevelEdit.setGeometry(QtCore.QRect(180, 70, 41, 20))
        self.MaxG_CrushLevelEdit.setObjectName("MaxG_CrushLevelEdit")
        self.MinG_CrushLevelEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinG_CrushLevelEdit.setGeometry(QtCore.QRect(120, 70, 41, 20))
        self.MinG_CrushLevelEdit.setObjectName("MinG_CrushLevelEdit")
        self.G_CrushLevelLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.G_CrushLevelLabel_2.setGeometry(QtCore.QRect(120, 50, 103, 14))
        self.G_CrushLevelLabel_2.setObjectName("G_CrushLevelLabel_2")
        self.MinG_GrainContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinG_GrainContentEdit.setGeometry(QtCore.QRect(10, 70, 41, 20))
        self.MinG_GrainContentEdit.setObjectName("MinG_GrainContentEdit")
        self.MinG_DensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinG_DensityEdit.setGeometry(QtCore.QRect(240, 68, 61, 20))
        self.MinG_DensityEdit.setObjectName("MinG_DensityEdit")
        self.MinG_SlitContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinG_SlitContentEdit.setGeometry(QtCore.QRect(420, 70, 41, 20))
        self.MinG_SlitContentEdit.setObjectName("MinG_SlitContentEdit")
        self.MaxG_SlitContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxG_SlitContentEdit.setGeometry(QtCore.QRect(480, 70, 41, 20))
        self.MaxG_SlitContentEdit.setObjectName("MaxG_SlitContentEdit")
        self.label_21 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_21.setGeometry(QtCore.QRect(300, 70, 16, 20))
        self.label_21.setObjectName("label_21")
        self.G_DensityLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.G_DensityLabel_2.setGeometry(QtCore.QRect(240, 50, 126, 12))
        self.G_DensityLabel_2.setObjectName("G_DensityLabel_2")
        self.MaxG_DensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxG_DensityEdit.setGeometry(QtCore.QRect(320, 70, 61, 20))
        self.MaxG_DensityEdit.setObjectName("MaxG_DensityEdit")
        self.label_23 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_23.setGeometry(QtCore.QRect(460, 70, 16, 20))
        self.label_23.setObjectName("label_23")
        self.G_SlitContentLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.G_SlitContentLabel_2.setGeometry(QtCore.QRect(420, 50, 78, 12))
        self.G_SlitContentLabel_2.setObjectName("G_SlitContentLabel_2")
        self.MinG_WaterContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinG_WaterContentEdit.setGeometry(QtCore.QRect(541, 70, 41, 20))
        self.MinG_WaterContentEdit.setObjectName("MinG_WaterContentEdit")
        self.label_25 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_25.setGeometry(QtCore.QRect(580, 70, 21, 20))
        self.label_25.setObjectName("label_25")
        self.MaxG_WaterContentEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxG_WaterContentEdit.setGeometry(QtCore.QRect(600, 70, 41, 20))
        self.MaxG_WaterContentEdit.setObjectName("MaxG_WaterContentEdit")
        self.G_WaterContentLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.G_WaterContentLabel_2.setGeometry(QtCore.QRect(541, 52, 78, 12))
        self.G_WaterContentLabel_2.setObjectName("G_WaterContentLabel_2")
        self.label_27 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_27.setGeometry(QtCore.QRect(50, 120, 21, 20))
        self.label_27.setObjectName("label_27")
        self.MaxA_DensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxA_DensityEdit.setGeometry(QtCore.QRect(70, 120, 41, 20))
        self.MaxA_DensityEdit.setObjectName("MaxA_DensityEdit")
        self.A_DensityLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.A_DensityLabel_2.setGeometry(QtCore.QRect(10, 102, 103, 12))
        self.A_DensityLabel_2.setObjectName("A_DensityLabel_2")
        self.MinA_DensityEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinA_DensityEdit.setGeometry(QtCore.QRect(10, 120, 41, 20))
        self.MinA_DensityEdit.setObjectName("MinA_DensityEdit")
        self.label_29 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_29.setGeometry(QtCore.QRect(160, 120, 21, 20))
        self.label_29.setObjectName("label_29")
        self.MaxR28_CompressionEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxR28_CompressionEdit.setGeometry(QtCore.QRect(330, 120, 41, 20))
        self.MaxR28_CompressionEdit.setObjectName("MaxR28_CompressionEdit")
        self.MinR7_CompressionEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinR7_CompressionEdit.setGeometry(QtCore.QRect(120, 118, 41, 20))
        self.MinR7_CompressionEdit.setObjectName("MinR7_CompressionEdit")
        self.MaxR7_CompressionEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MaxR7_CompressionEdit.setGeometry(QtCore.QRect(190, 120, 41, 20))
        self.MaxR7_CompressionEdit.setObjectName("MaxR7_CompressionEdit")
        self.MinR28_CompressionEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.MinR28_CompressionEdit.setGeometry(QtCore.QRect(254, 120, 41, 20))
        self.MinR28_CompressionEdit.setObjectName("MinR28_CompressionEdit")
        self.R28_CompressionLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.R28_CompressionLabel_2.setGeometry(QtCore.QRect(254, 102, 126, 12))
        self.R28_CompressionLabel_2.setObjectName("R28_CompressionLabel_2")
        self.label_31 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_31.setGeometry(QtCore.QRect(300, 120, 21, 20))
        self.label_31.setObjectName("label_31")
        self.R7_CompressionLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.R7_CompressionLabel_2.setGeometry(QtCore.QRect(120, 100, 132, 12))
        self.R7_CompressionLabel_2.setObjectName("R7_CompressionLabel_2")
        self.Project7ConDesignSpeciEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.Project7ConDesignSpeciEdit.setGeometry(QtCore.QRect(460, 120, 201, 20))
        self.Project7ConDesignSpeciEdit.setObjectName("Project7ConDesignSpeciEdit")
        self.ConDesignSpeciLabel = QtWidgets.QLabel(self.ConMixDesignPage)
        self.ConDesignSpeciLabel.setGeometry(QtCore.QRect(400, 120, 71, 16))
        self.ConDesignSpeciLabel.setObjectName("ConDesignSpeciLabel")
        self.label_86 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_86.setGeometry(QtCore.QRect(220, 180, 31, 16))
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_87.setGeometry(QtCore.QRect(10, 180, 71, 16))
        self.label_87.setObjectName("label_87")
        self.Project7try = QtWidgets.QComboBox(self.ConMixDesignPage)
        self.Project7try.setGeometry(QtCore.QRect(440, 180, 81, 22))
        self.Project7try.setObjectName("Project7try")
        self.Project7Manager = QtWidgets.QComboBox(self.ConMixDesignPage)
        self.Project7Manager.setGeometry(QtCore.QRect(90, 180, 81, 22))
        self.Project7Manager.setObjectName("Project7Manager")
        self.label_88 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.label_88.setGeometry(QtCore.QRect(380, 180, 51, 16))
        self.label_88.setObjectName("label_88")
        self.Project7Checker = QtWidgets.QComboBox(self.ConMixDesignPage)
        self.Project7Checker.setGeometry(QtCore.QRect(260, 180, 81, 22))
        self.Project7Checker.setObjectName("Project7Checker")
        self.Project7CodeEdit = QtWidgets.QLineEdit(self.ConMixDesignPage)
        self.Project7CodeEdit.setGeometry(QtCore.QRect(100, 150, 201, 20))
        self.Project7CodeEdit.setObjectName("Project7CodeEdit")
        self.ConDesignSpeciLabel_2 = QtWidgets.QLabel(self.ConMixDesignPage)
        self.ConDesignSpeciLabel_2.setGeometry(QtCore.QRect(10, 150, 71, 20))
        self.ConDesignSpeciLabel_2.setObjectName("ConDesignSpeciLabel_2")
        self.toolBox.addItem(self.ConMixDesignPage, "")
        self.ConUseProvePage = QtWidgets.QWidget()
        self.ConUseProvePage.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.ConUseProvePage.setObjectName("ConUseProvePage")
        self.toolBox.addItem(self.ConUseProvePage, "")
        self.ConQualityRecordPage = QtWidgets.QWidget()
        self.ConQualityRecordPage.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.ConQualityRecordPage.setObjectName("ConQualityRecordPage")
        self.S_SlitContentLabel_3 = QtWidgets.QLabel(self.ConQualityRecordPage)
        self.S_SlitContentLabel_3.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.S_SlitContentLabel_3.setObjectName("S_SlitContentLabel_3")
        self.G_SlitContentLabel_3 = QtWidgets.QLabel(self.ConQualityRecordPage)
        self.G_SlitContentLabel_3.setGeometry(QtCore.QRect(150, 30, 121, 16))
        self.G_SlitContentLabel_3.setObjectName("G_SlitContentLabel_3")
        self.G_WaterContentLabel_5 = QtWidgets.QLabel(self.ConQualityRecordPage)
        self.G_WaterContentLabel_5.setGeometry(QtCore.QRect(70, 0, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.G_WaterContentLabel_5.setFont(font)
        self.G_WaterContentLabel_5.setObjectName("G_WaterContentLabel_5")
        self.label_60 = QtWidgets.QLabel(self.ConQualityRecordPage)
        self.label_60.setGeometry(QtCore.QRect(200, 60, 51, 20))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.ConQualityRecordPage)
        self.label_61.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_61.setObjectName("label_61")
        self.Project9Record = QtWidgets.QComboBox(self.ConQualityRecordPage)
        self.Project9Record.setGeometry(QtCore.QRect(440, 60, 81, 22))
        self.Project9Record.setObjectName("Project9Record")
        self.Project9Manager = QtWidgets.QComboBox(self.ConQualityRecordPage)
        self.Project9Manager.setGeometry(QtCore.QRect(90, 60, 81, 22))
        self.Project9Manager.setObjectName("Project9Manager")
        self.label_62 = QtWidgets.QLabel(self.ConQualityRecordPage)
        self.label_62.setGeometry(QtCore.QRect(380, 60, 51, 16))
        self.label_62.setObjectName("label_62")
        self.Project9Checker = QtWidgets.QComboBox(self.ConQualityRecordPage)
        self.Project9Checker.setGeometry(QtCore.QRect(260, 60, 81, 22))
        self.Project9Checker.setObjectName("Project9Checker")
        self.toolBox.addItem(self.ConQualityRecordPage, "")
        self.PermeabilityTestReportPage = QtWidgets.QWidget()
        self.PermeabilityTestReportPage.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.PermeabilityTestReportPage.setObjectName("PermeabilityTestReportPage")
        self.Inspection_BasisLabel = QtWidgets.QLabel(self.PermeabilityTestReportPage)
        self.Inspection_BasisLabel.setGeometry(QtCore.QRect(0, 10, 61, 16))
        self.Inspection_BasisLabel.setObjectName("Inspection_BasisLabel")
        self.Project10ConTestReportTestBasisEdit = QtWidgets.QLineEdit(self.PermeabilityTestReportPage)
        self.Project10ConTestReportTestBasisEdit.setGeometry(QtCore.QRect(70, 10, 131, 20))
        self.Project10ConTestReportTestBasisEdit.setObjectName("Project10ConTestReportTestBasisEdit")
        self.Inspection_UnitLabel = QtWidgets.QLabel(self.PermeabilityTestReportPage)
        self.Inspection_UnitLabel.setGeometry(QtCore.QRect(260, 10, 71, 16))
        self.Inspection_UnitLabel.setObjectName("Inspection_UnitLabel")
        self.Project10InspectCodeEdit = QtWidgets.QLineEdit(self.PermeabilityTestReportPage)
        self.Project10InspectCodeEdit.setGeometry(QtCore.QRect(320, 10, 151, 20))
        self.Project10InspectCodeEdit.setObjectName("Project10InspectCodeEdit")
        self.label_4 = QtWidgets.QLabel(self.PermeabilityTestReportPage)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_4.setObjectName("label_4")
        self.Project10Manager = QtWidgets.QComboBox(self.PermeabilityTestReportPage)
        self.Project10Manager.setGeometry(QtCore.QRect(90, 110, 81, 22))
        self.Project10Manager.setObjectName("Project10Manager")
        self.label_6 = QtWidgets.QLabel(self.PermeabilityTestReportPage)
        self.label_6.setGeometry(QtCore.QRect(220, 110, 31, 16))
        self.label_6.setObjectName("label_6")
        self.Project10Examine = QtWidgets.QComboBox(self.PermeabilityTestReportPage)
        self.Project10Examine.setGeometry(QtCore.QRect(260, 110, 81, 22))
        self.Project10Examine.setObjectName("Project10Examine")
        self.label_7 = QtWidgets.QLabel(self.PermeabilityTestReportPage)
        self.label_7.setGeometry(QtCore.QRect(380, 110, 51, 16))
        self.label_7.setObjectName("label_7")
        self.Project10Checker = QtWidgets.QComboBox(self.PermeabilityTestReportPage)
        self.Project10Checker.setGeometry(QtCore.QRect(440, 110, 81, 22))
        self.Project10Checker.setObjectName("Project10Checker")
        self.CreepLabel = QtWidgets.QLabel(self.PermeabilityTestReportPage)
        self.CreepLabel.setGeometry(QtCore.QRect(380, 50, 91, 16))
        self.CreepLabel.setObjectName("CreepLabel")
        self.Project10MaxCreepEdit = QtWidgets.QLineEdit(self.PermeabilityTestReportPage)
        self.Project10MaxCreepEdit.setGeometry(QtCore.QRect(440, 70, 41, 20))
        self.Project10MaxCreepEdit.setObjectName("Project10MaxCreepEdit")
        self.Project10MinCreepEdit = QtWidgets.QLineEdit(self.PermeabilityTestReportPage)
        self.Project10MinCreepEdit.setGeometry(QtCore.QRect(380, 70, 51, 20))
        self.Project10MinCreepEdit.setObjectName("Project10MinCreepEdit")
        self.label_59 = QtWidgets.QLabel(self.PermeabilityTestReportPage)
        self.label_59.setGeometry(QtCore.QRect(430, 70, 21, 16))
        self.label_59.setObjectName("label_59")
        self.Project10TimeEdit = QtWidgets.QTimeEdit(self.PermeabilityTestReportPage)
        self.Project10TimeEdit.setGeometry(QtCore.QRect(110, 60, 61, 22))
        self.Project10TimeEdit.setObjectName("Project10TimeEdit")
        self.label_10 = QtWidgets.QLabel(self.PermeabilityTestReportPage)
        self.label_10.setGeometry(QtCore.QRect(0, 60, 111, 16))
        self.label_10.setObjectName("label_10")
        self.toolBox.addItem(self.PermeabilityTestReportPage, "")
        self.MixProportionPage = QtWidgets.QWidget()
        self.MixProportionPage.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.MixProportionPage.setObjectName("MixProportionPage")
        self.S_FinenessDensityLabel_3 = QtWidgets.QLabel(self.MixProportionPage)
        self.S_FinenessDensityLabel_3.setGeometry(QtCore.QRect(0, 30, 84, 12))
        self.S_FinenessDensityLabel_3.setObjectName("S_FinenessDensityLabel_3")
        self.S_SlitContentLabel_4 = QtWidgets.QLabel(self.MixProportionPage)
        self.S_SlitContentLabel_4.setGeometry(QtCore.QRect(110, 30, 84, 14))
        self.S_SlitContentLabel_4.setObjectName("S_SlitContentLabel_4")
        self.G_SlitContentLabel_4 = QtWidgets.QLabel(self.MixProportionPage)
        self.G_SlitContentLabel_4.setGeometry(QtCore.QRect(330, 30, 78, 12))
        self.G_SlitContentLabel_4.setObjectName("G_SlitContentLabel_4")
        self.S_WaterContentLabel_3 = QtWidgets.QLabel(self.MixProportionPage)
        self.S_WaterContentLabel_3.setGeometry(QtCore.QRect(230, 30, 78, 14))
        self.S_WaterContentLabel_3.setObjectName("S_WaterContentLabel_3")
        self.G_WaterContentLabel_3 = QtWidgets.QLabel(self.MixProportionPage)
        self.G_WaterContentLabel_3.setGeometry(QtCore.QRect(430, 30, 78, 12))
        self.G_WaterContentLabel_3.setObjectName("G_WaterContentLabel_3")
        self.G_WaterContentLabel_4 = QtWidgets.QLabel(self.MixProportionPage)
        self.G_WaterContentLabel_4.setGeometry(QtCore.QRect(180, 0, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.G_WaterContentLabel_4.setFont(font)
        self.G_WaterContentLabel_4.setObjectName("G_WaterContentLabel_4")
        self.Project11Manager = QtWidgets.QComboBox(self.MixProportionPage)
        self.Project11Manager.setGeometry(QtCore.QRect(80, 60, 81, 22))
        self.Project11Manager.setObjectName("Project11Manager")
        self.label_11 = QtWidgets.QLabel(self.MixProportionPage)
        self.label_11.setGeometry(QtCore.QRect(370, 60, 51, 16))
        self.label_11.setObjectName("label_11")
        self.Project11Checker = QtWidgets.QComboBox(self.MixProportionPage)
        self.Project11Checker.setGeometry(QtCore.QRect(430, 60, 81, 22))
        self.Project11Checker.setObjectName("Project11Checker")
        self.label_12 = QtWidgets.QLabel(self.MixProportionPage)
        self.label_12.setGeometry(QtCore.QRect(0, 60, 71, 16))
        self.label_12.setObjectName("label_12")
        self.toolBox.addItem(self.MixProportionPage, "")
        self.gridLayout_2.addWidget(self.toolBox, 1, 1, 1, 7)
        self.ChoicConcreteUsageRecordButton = QtWidgets.QPushButton(self.OutExcelPage)
        self.ChoicConcreteUsageRecordButton.setObjectName("ChoicConcreteUsageRecordButton")
        self.gridLayout_2.addWidget(self.ChoicConcreteUsageRecordButton, 0, 7, 1, 1)
        self.OutPutVoidButton = QtWidgets.QPushButton(self.OutExcelPage)
        self.OutPutVoidButton.setEnabled(False)
        self.OutPutVoidButton.setObjectName("OutPutVoidButton")
        self.gridLayout_2.addWidget(self.OutPutVoidButton, 2, 7, 1, 1)
        self.stackedWidget.addWidget(self.OutExcelPage)
        self.InSQLPage = QtWidgets.QWidget()
        self.InSQLPage.setObjectName("InSQLPage")
        self.CementInfoButton = QtWidgets.QPushButton(self.InSQLPage)
        self.CementInfoButton.setGeometry(QtCore.QRect(490, 100, 209, 23))
        self.CementInfoButton.setObjectName("CementInfoButton")
        self.CementInfoPath = QtWidgets.QLineEdit(self.InSQLPage)
        self.CementInfoPath.setGeometry(QtCore.QRect(287, 101, 171, 20))
        self.CementInfoPath.setDragEnabled(False)
        self.CementInfoPath.setReadOnly(True)
        self.CementInfoPath.setObjectName("CementInfoPath")
        self.CementInfoLabel = QtWidgets.QLabel(self.InSQLPage)
        self.CementInfoLabel.setGeometry(QtCore.QRect(56, 100, 177, 23))
        self.CementInfoLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.CementInfoLabel.setObjectName("CementInfoLabel")
        self.MixPoportionPath = QtWidgets.QLineEdit(self.InSQLPage)
        self.MixPoportionPath.setGeometry(QtCore.QRect(291, 281, 171, 20))
        self.MixPoportionPath.setDragEnabled(False)
        self.MixPoportionPath.setReadOnly(True)
        self.MixPoportionPath.setObjectName("MixPoportionPath")
        self.MixPoportionLabel = QtWidgets.QLabel(self.InSQLPage)
        self.MixPoportionLabel.setGeometry(QtCore.QRect(60, 280, 177, 23))
        self.MixPoportionLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.MixPoportionLabel.setObjectName("MixPoportionLabel")
        self.MixPoportionButton = QtWidgets.QPushButton(self.InSQLPage)
        self.MixPoportionButton.setGeometry(QtCore.QRect(494, 280, 209, 23))
        self.MixPoportionButton.setObjectName("MixPoportionButton")
        self.stackedWidget.addWidget(self.InSQLPage)
        self.OutSQLPage = QtWidgets.QWidget()
        self.OutSQLPage.setObjectName("OutSQLPage")
        self.OutSQLLabel = QtWidgets.QLabel(self.OutSQLPage)
        self.OutSQLLabel.setGeometry(QtCore.QRect(80, 130, 177, 61))
        self.OutSQLLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.OutSQLLabel.setObjectName("OutSQLLabel")
        self.OutSQLPath = QtWidgets.QLineEdit(self.OutSQLPage)
        self.OutSQLPath.setEnabled(False)
        self.OutSQLPath.setGeometry(QtCore.QRect(297, 161, 171, 20))
        self.OutSQLPath.setDragEnabled(False)
        self.OutSQLPath.setReadOnly(True)
        self.OutSQLPath.setObjectName("OutSQLPath")
        self.OutSQLButton_2 = QtWidgets.QPushButton(self.OutSQLPage)
        self.OutSQLButton_2.setGeometry(QtCore.QRect(500, 160, 209, 23))
        self.OutSQLButton_2.setObjectName("OutSQLButton_2")
        self.OutSQLButton_3 = QtWidgets.QPushButton(self.OutSQLPage)
        self.OutSQLButton_3.setEnabled(False)
        self.OutSQLButton_3.setGeometry(QtCore.QRect(330, 270, 75, 23))
        self.OutSQLButton_3.setObjectName("OutSQLButton_3")
        self.stackedWidget.addWidget(self.OutSQLPage)
        self.Cementpage = QtWidgets.QWidget()
        self.Cementpage.setObjectName("Cementpage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Cementpage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.CementIdEdit_2 = QtWidgets.QLineEdit(self.Cementpage)
        self.CementIdEdit_2.setObjectName("CementIdEdit_2")
        self.gridLayout_3.addWidget(self.CementIdEdit_2, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.Cementpage)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Cementpage)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 0, 1, 1)
        self.IsPriorityEdit = QtWidgets.QLineEdit(self.Cementpage)
        self.IsPriorityEdit.setObjectName("IsPriorityEdit")
        self.gridLayout_3.addWidget(self.IsPriorityEdit, 2, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 1, 9, 1, 1)
        self.CementtableView = QtWidgets.QTableView(self.Cementpage)
        self.CementtableView.setObjectName("CementtableView")
        self.gridLayout_3.addWidget(self.CementtableView, 0, 0, 1, 12)
        self.CementdelButton = QtWidgets.QPushButton(self.Cementpage)
        self.CementdelButton.setObjectName("CementdelButton")
        self.gridLayout_3.addWidget(self.CementdelButton, 1, 10, 1, 1)
        self.CementQueryButton = QtWidgets.QPushButton(self.Cementpage)
        self.CementQueryButton.setObjectName("CementQueryButton")
        self.gridLayout_3.addWidget(self.CementQueryButton, 2, 2, 1, 1)
        self.CementsubmitButton = QtWidgets.QPushButton(self.Cementpage)
        self.CementsubmitButton.setObjectName("CementsubmitButton")
        self.gridLayout_3.addWidget(self.CementsubmitButton, 1, 5, 1, 1)
        self.CementrefreshButton = QtWidgets.QPushButton(self.Cementpage)
        self.CementrefreshButton.setObjectName("CementrefreshButton")
        self.gridLayout_3.addWidget(self.CementrefreshButton, 2, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(84, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 2, 3, 1, 1)
        self.deletArtButton = QtWidgets.QPushButton(self.Cementpage)
        self.deletArtButton.setObjectName("deletArtButton")
        self.gridLayout_3.addWidget(self.deletArtButton, 2, 10, 1, 1)
        self.CementAddButton = QtWidgets.QPushButton(self.Cementpage)
        self.CementAddButton.setObjectName("CementAddButton")
        self.gridLayout_3.addWidget(self.CementAddButton, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.Cementpage)
        self.MixInfopage = QtWidgets.QWidget()
        self.MixInfopage.setObjectName("MixInfopage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.MixInfopage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 2, 3, 1, 1)
        self.mixsubmitButton = QtWidgets.QPushButton(self.MixInfopage)
        self.mixsubmitButton.setObjectName("mixsubmitButton")
        self.gridLayout_4.addWidget(self.mixsubmitButton, 2, 4, 1, 1)
        self.MixtableView = QtWidgets.QTableView(self.MixInfopage)
        self.MixtableView.setObjectName("MixtableView")
        self.gridLayout_4.addWidget(self.MixtableView, 0, 0, 1, 8)
        self.label_26 = QtWidgets.QLabel(self.MixInfopage)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 2, 0, 1, 1)
        self.MixIdEdit = QtWidgets.QLineEdit(self.MixInfopage)
        self.MixIdEdit.setObjectName("MixIdEdit")
        self.gridLayout_4.addWidget(self.MixIdEdit, 2, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(537, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 1, 2, 1, 6)
        self.MixNameEdit = QtWidgets.QLineEdit(self.MixInfopage)
        self.MixNameEdit.setObjectName("MixNameEdit")
        self.gridLayout_4.addWidget(self.MixNameEdit, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.MixInfopage)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.MixLevelEdit = QtWidgets.QLineEdit(self.MixInfopage)
        self.MixLevelEdit.setObjectName("MixLevelEdit")
        self.gridLayout_4.addWidget(self.MixLevelEdit, 4, 1, 1, 1)
        self.MixqueryButton = QtWidgets.QPushButton(self.MixInfopage)
        self.MixqueryButton.setObjectName("MixqueryButton")
        self.gridLayout_4.addWidget(self.MixqueryButton, 4, 2, 1, 1)
        self.MixStrengthEdit = QtWidgets.QLineEdit(self.MixInfopage)
        self.MixStrengthEdit.setObjectName("MixStrengthEdit")
        self.gridLayout_4.addWidget(self.MixStrengthEdit, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.MixInfopage)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.MixInfopage)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 4, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(92, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 2, 7, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 2, 5, 1, 1)
        self.deleMIXButton = QtWidgets.QPushButton(self.MixInfopage)
        self.deleMIXButton.setObjectName("deleMIXButton")
        self.gridLayout_4.addWidget(self.deleMIXButton, 4, 6, 1, 1)
        self.mixAddButton = QtWidgets.QPushButton(self.MixInfopage)
        self.mixAddButton.setObjectName("mixAddButton")
        self.gridLayout_4.addWidget(self.mixAddButton, 2, 2, 1, 1)
        self.mixrefreshButton = QtWidgets.QPushButton(self.MixInfopage)
        self.mixrefreshButton.setObjectName("mixrefreshButton")
        self.gridLayout_4.addWidget(self.mixrefreshButton, 4, 4, 1, 1)
        self.MixDelButton = QtWidgets.QPushButton(self.MixInfopage)
        self.MixDelButton.setObjectName("MixDelButton")
        self.gridLayout_4.addWidget(self.MixDelButton, 2, 6, 1, 1)
        self.stackedWidget.addWidget(self.MixInfopage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.MenuWidget.raise_()
        self.stackedWidget.raise_()
        self.line.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "建筑业务系统"))
        self.MixpushButton.setText(_translate("Form", "配合比表信息"))
        self.OutputLabel.setText(_translate("Form", "输出："))
        self.OutPutSQLButton.setText(_translate("Form", "数据库内容导出"))
        self.OutExcelButton.setText(_translate("Form", "导出表格"))
        self.CementDateButton.setText(_translate("Form", "水泥一览表信息"))
        self.InSQLButton.setText(_translate("Form", "Excel导入信息"))
        self.BasicInformationLabel.setText(_translate("Form", "基本信息："))
        self.ChangePrarmerButton.setText(_translate("Form", "确定修改参数"))
        self.OutPutButton.setToolTip(_translate("Form", "<html><head/><body><p>选择混凝土使用记录表才能点击此按钮</p></body></html>"))
        self.OutPutButton.setText(_translate("Form", "确认导出"))
        self.ConcreteUsageRecordLabel.setText(_translate("Form", "混凝土使用记录表："))
        self.label_2.setText(_translate("Form", "工程负责人："))
        self.label_3.setText(_translate("Form", "填表人："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ConUseBuyRecordPage), _translate("Form", "1、水泥购进、使用一览表"))
        self.C_Strengthlabel.setText(_translate("Form", "个体水泥强度等级系数区间"))
        self.linelabel_1.setText(_translate("Form", " -----"))
        self.label_93.setText(_translate("Form", "单位检验工程负责人："))
        self.label_94.setText(_translate("Form", "校核："))
        self.label_95.setText(_translate("Form", "检验："))
        self.Inspection_UnitLabel_4.setText(_translate("Form", "省统表号："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ConStrengReportPage), _translate("Form", "2、混凝土试件抗压强度检验报告"))
        self.label_92.setText(_translate("Form", "制表："))
        self.Inspection_UnitLabel_3.setText(_translate("Form", "省统表号："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ConStrengReportSumPage), _translate("Form", "3、混凝土试块强度试验结果汇总表"))
        self.label_89.setText(_translate("Form", "复核："))
        self.label_90.setText(_translate("Form", "单位工程负责人："))
        self.label_91.setText(_translate("Form", "计算："))
        self.Inspection_UnitLabel_2.setText(_translate("Form", "省统表号："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ConStrengReportCompPage), _translate("Form", "4、标准养护混凝土抗压强度计算表"))
        self.label_14.setText(_translate("Form", "技术负责人："))
        self.label_16.setText(_translate("Form", "填表人"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.CreateConFacyoryCardPage), _translate("Form", "5、建友商品混凝土出厂合格证"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.SlumpCardPage), _translate("Form", "6、混凝土坍落度验收表"))
        self.label_5.setText(_translate("Form", " -----"))
        self.label_8.setText(_translate("Form", " -----"))
        self.S_FinenessDensityLabel.setText(_translate("Form", "砂细度模数区间"))
        self.S_SurfaceDensityLabel.setText(_translate("Form", "砂表面密度区间"))
        self.label_9.setText(_translate("Form", " -----"))
        self.S_DensityLabel.setText(_translate("Form", "砂堆积密度区间"))
        self.S_SlitContentLabel_2.setText(_translate("Form", "砂含泥量区间"))
        self.label_13.setText(_translate("Form", " -----"))
        self.label_15.setText(_translate("Form", " -----"))
        self.S_WaterContentLabel_2.setText(_translate("Form", "砂含水量区间"))
        self.G_GrainContentLabel_2.setText(_translate("Form", "石颗粒含量区间"))
        self.label_17.setText(_translate("Form", " -----"))
        self.label_19.setText(_translate("Form", " -----"))
        self.G_CrushLevelLabel_2.setText(_translate("Form", "石压碎指标区间"))
        self.label_21.setText(_translate("Form", " -----"))
        self.G_DensityLabel_2.setText(_translate("Form", "石堆积密度区间"))
        self.label_23.setText(_translate("Form", " -----"))
        self.G_SlitContentLabel_2.setText(_translate("Form", "石含泥量区间"))
        self.label_25.setText(_translate("Form", " -----"))
        self.G_WaterContentLabel_2.setText(_translate("Form", "石含水量区间"))
        self.label_27.setText(_translate("Form", " -----"))
        self.A_DensityLabel_2.setText(_translate("Form", "掺合料浓度区间"))
        self.label_29.setText(_translate("Form", " -----"))
        self.R28_CompressionLabel_2.setText(_translate("Form", "配合比抗压强度28d区间"))
        self.label_31.setText(_translate("Form", " -----"))
        self.R7_CompressionLabel_2.setText(_translate("Form", "配合比抗压强度7d区间"))
        self.ConDesignSpeciLabel.setText(_translate("Form", "检评依据："))
        self.label_86.setText(_translate("Form", "校核："))
        self.label_87.setText(_translate("Form", "技术负责人："))
        self.label_88.setText(_translate("Form", "试验："))
        self.ConDesignSpeciLabel_2.setText(_translate("Form", "省统表编号："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ConMixDesignPage), _translate("Form", "7、混凝土配合比设计报告"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ConUseProvePage), _translate("Form", "8、工地使用预拌混凝土证明书"))
        self.S_SlitContentLabel_3.setText(_translate("Form", "砂含泥量区间"))
        self.G_SlitContentLabel_3.setText(_translate("Form", "石含泥量区间"))
        self.G_WaterContentLabel_5.setText(_translate("Form", "请在表7中修改"))
        self.label_60.setText(_translate("Form", "质检员："))
        self.label_61.setText(_translate("Form", "工程负责人："))
        self.label_62.setText(_translate("Form", "记录："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ConQualityRecordPage), _translate("Form", "9、混凝土搅拌质量记录表"))
        self.Inspection_BasisLabel.setText(_translate("Form", "检验依据："))
        self.Inspection_UnitLabel.setText(_translate("Form", "省统表号："))
        self.label_4.setText(_translate("Form", "技术负责人："))
        self.label_6.setText(_translate("Form", "审核："))
        self.label_7.setText(_translate("Form", "检验人："))
        self.CreepLabel.setText(_translate("Form", "最高渗水值区间："))
        self.label_59.setText(_translate("Form", "-"))
        self.label_10.setText(_translate("Form", "加水压日期的时分："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.PermeabilityTestReportPage), _translate("Form", "10、抗渗性能检测报告"))
        self.S_FinenessDensityLabel_3.setText(_translate("Form", "砂细度模数区间"))
        self.S_SlitContentLabel_4.setText(_translate("Form", "砂含泥量区间"))
        self.G_SlitContentLabel_4.setText(_translate("Form", "石含泥量区间"))
        self.S_WaterContentLabel_3.setText(_translate("Form", "砂含水量区间"))
        self.G_WaterContentLabel_3.setText(_translate("Form", "石含水量区间"))
        self.G_WaterContentLabel_4.setText(_translate("Form", "请在表7中修改"))
        self.label_11.setText(_translate("Form", "试验："))
        self.label_12.setText(_translate("Form", "技术负责人："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.MixProportionPage), _translate("Form", "11、施工配合比"))
        self.ChoicConcreteUsageRecordButton.setText(_translate("Form", "选择文件"))
        self.OutPutVoidButton.setText(_translate("Form", "导出空白模板"))
        self.CementInfoButton.setText(_translate("Form", "选择文件"))
        self.CementInfoLabel.setText(_translate("Form", "水泥资料一览表："))
        self.MixPoportionLabel.setText(_translate("Form", "配合比选用汇总表："))
        self.MixPoportionButton.setText(_translate("Form", "选择文件"))
        self.OutSQLLabel.setText(_translate("Form", "导出：\n"
"水泥资料一览表\n"
"配合比选用汇总表"))
        self.OutSQLButton_2.setText(_translate("Form", "选择文件"))
        self.OutSQLButton_3.setText(_translate("Form", "确定导出"))
        self.label_22.setText(_translate("Form", "是否优先（0、1）"))
        self.label_20.setText(_translate("Form", "编号："))
        self.CementdelButton.setText(_translate("Form", "删除"))
        self.CementQueryButton.setText(_translate("Form", "查询"))
        self.CementsubmitButton.setText(_translate("Form", "提交"))
        self.CementrefreshButton.setText(_translate("Form", "刷新"))
        self.deletArtButton.setText(_translate("Form", "清空此表"))
        self.CementAddButton.setText(_translate("Form", "添加"))
        self.mixsubmitButton.setText(_translate("Form", "提交"))
        self.label_26.setText(_translate("Form", "配合比编号："))
        self.label_24.setText(_translate("Form", "名称："))
        self.MixqueryButton.setText(_translate("Form", "查询"))
        self.label_28.setText(_translate("Form", "强度等级："))
        self.label_30.setText(_translate("Form", "抗渗等级："))
        self.deleMIXButton.setText(_translate("Form", "清空此表"))
        self.mixAddButton.setText(_translate("Form", "添加"))
        self.mixrefreshButton.setText(_translate("Form", "刷新"))
        self.MixDelButton.setText(_translate("Form", "删除"))

